// <auto-generated/>
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Huellitas.Data.Migrations
{
    public partial class AddColumn_FriendlyName_Table_Content : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "FriendlyName",
                table: "Content",
                nullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "ParentLocationId",
                table: "Location",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Location_ParentLocationId",
                table: "Location",
                column: "ParentLocationId");

            migrationBuilder.CreateIndex(
                name: "IX_Content_FriendlyName",
                table: "Content",
                column: "FriendlyName",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Location_Location_ParentLocationId",
                table: "Location",
                column: "ParentLocationId",
                principalTable: "Location",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Location_Location_ParentLocationId",
                table: "Location");

            migrationBuilder.DropIndex(
                name: "IX_Location_ParentLocationId",
                table: "Location");

            migrationBuilder.DropIndex(
                name: "IX_Content_FriendlyName",
                table: "Content");

            migrationBuilder.DropColumn(
                name: "FriendlyName",
                table: "Content");

            migrationBuilder.AlterColumn<int>(
                name: "ParentLocationId",
                table: "Location",
                nullable: false);
        }
    }
}
