// <auto-generated/>
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Huellitas.Data.Migrations
{
    public partial class AlterColumn_ShortMessage_FullMessage_Table_Log : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(name: "ShortMessage", table: "Logs", type: "nvarchar(max)");
            migrationBuilder.AlterColumn<string>(name: "FullMessage", table: "Logs", type: "nvarchar(max)");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(name: "ShortMessage", table: "Logs", type: "nvarchar(4000)");
            migrationBuilder.AlterColumn<string>(name: "FullMessage", table: "Logs", type: "nvarchar(4000)");
        }
    }
}
