// <auto-generated/>
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Huellitas.Data.Migrations
{
    public partial class AddColumn_ParentCustomTableRowId_Table_CustomTableRow : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ParentCustomTableRowId",
                table: "CustomTableRows",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_CustomTableRows_ParentCustomTableRowId",
                table: "CustomTableRows",
                column: "ParentCustomTableRowId");

            migrationBuilder.AddForeignKey(
                name: "FK_CustomTableRows_CustomTableRows_ParentCustomTableRowId",
                table: "CustomTableRows",
                column: "ParentCustomTableRowId",
                principalTable: "CustomTableRows",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CustomTableRows_CustomTableRows_ParentCustomTableRowId",
                table: "CustomTableRows");

            migrationBuilder.DropIndex(
                name: "IX_CustomTableRows_ParentCustomTableRowId",
                table: "CustomTableRows");

            migrationBuilder.DropColumn(
                name: "ParentCustomTableRowId",
                table: "CustomTableRows");
        }
    }
}
