// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace Huellitas.Data.Migrations
{
    public partial class UpdateRecords_Questions_Table_CustomTableRow : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True|No entregues animales a personas que lo quieren cómo regalos para niños, o que sean para otra persona diferente a la que lo solicita en adopción' where Id = 10");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True|Si tu perro o gato no se lleva bien con otros animales, ten en cuenta esto.' where Id = 173");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True|No entregues animales que duerman en terrazas o patios.' where Id = 174");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'SingleWithOther|Soy Responsable,Madre,Padre|True|No entregues a personas menores de 23 años que llenen el formulario y se hagan ellos mismos responsables.' where Id = 175");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Nunca,2 a 4 horas,4 a 6 horas,Más de 6 horas|True|No es recomendable que el perro se quede más de 6 horas solo' where Id = 176");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Apartamento,Casa,Finca,Bodega|True|Si tu perro es muy grande no es recomendable entregarlo a un apartamento' where Id = 177");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True|Si ha tenido mascotas por mucho tiempo es un gran punto a favor' where Id = 178");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True|' where Id = 179");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True|' where Id = 180");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True|' where Id = 181");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True|' where Id = 182");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True|' where Id = 183");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Casa propia,Arriendo|True|Preguntale si el arrendador ya le autorizó tener mascotas en su casa. Ten en cuenta que la gente que vive en arriendo y se cambia de lugar en muchas ocasiones el arrendador no le permite tener el animal. Esto genera abandono.' where Id = 184");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Hasta $20.000,Entre $20.000 y $50.000,Entre $50.000 y $80.000,Más de 80.000 pesos|True|Con menos de $50.000 mensuales es muy complicado mantener una mascota. Esto puede denotar desconocimiento en la tenencia de los animales.' where Id = 185");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'ChecksWithText|Perro,Gato,Otro|True|' where Id = 270");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'OptionsWithText|Especie,Cuanto tiempo vivió contigo?,¿En dónde está el animal?|True|Si la anterior mascota fue regalada a otra familia NO apruebes el formulario.' where Id = 271");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True' where Id = 10");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True' where Id = 173");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True' where Id = 174");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'SingleWithOther|Soy Responsable,Madre,Padre|True' where Id = 175");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Nunca,2 a 4 horas,4 a 6 horas,Más de 6 horas|True' where Id = 176");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Apartamento,Casa,Finca,Bodega|True' where Id = 177");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True' where Id = 178");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True' where Id = 179");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Text||True' where Id = 180");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True' where Id = 181");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True' where Id = 182");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Boolean||True' where Id = 183");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Casa propia,Arriendo|True' where Id = 184");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'Single|Hasta $20.000,Entre $20.000 y $50.000,Entre $50.000 y $80.000,Más de 80.000 pesos|True' where Id = 185");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'ChecksWithText|Perro,Gato,Otro|True' where Id = 270");
            migrationBuilder.Sql($"update CustomTableRows set AdditionalInfo = 'OptionsWithText|Especie,Cuanto tiempo vivió contigo?,¿En dónde está el animal?|True' where Id = 271");
        }
    }
}
