// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace Huellitas.Data.Migrations
{
    public partial class AlterColumn_AdditionalInfo_Table_CustomTableRow : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "TargetURL",
                table: "SystemNotifications",
                newName: "TargetUrl");

            migrationBuilder.AlterColumn<string>(
                name: "AdditionalInfo",
                table: "CustomTableRows",
                type: "varchar(1500)",
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 100,
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "TargetUrl",
                table: "SystemNotifications",
                newName: "TargetURL");

            migrationBuilder.AlterColumn<string>(
                name: "AdditionalInfo",
                table: "CustomTableRows",
                maxLength: 100,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(1500)",
                oldNullable: true);
        }
    }
}
